Repository illuminatus52/Team-C-Unit-Conversion-API, pull requests merged in 2022-03, with the labels that each got.

#8 creates controller and endpoint
  .idea/.gitignore
  Unit_Conversion/Unit_Conversion.iml
  Unit_Conversion/src/main/java/com/unit_conversion/controller/ConverterController.java
Labels: good first issue

#11 creates Interface ConvertService, and Service ConverterService
  Unit_Conversion/src/main/java/com/unit_conversion/UnitConversionApplication.java
  Unit_Conversion/src/main/java/com/unit_conversion/service/ConvertService.java
  Unit_Conversion/src/main/java/com/unit_conversion/service/ConverterService.java
Labels: enhancement

#20 fixes NullPointerException in Controller
  .gitignore
  src/main/java/com/unit_conversion/controller/ConverterController.java
Labels: bug

#21 adds postman collection
  src/test/resources/Conversion API.postman_collection.json
Labels: enhancement
